apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongoauth
spec:
  members: 1
  type: ReplicaSet
  version: "6.0.12"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: test
      passwordSecretRef:
        name: mongo-admin-password
        key: password
      scramCredentialsSecretName: mongoauth
      roles:
        - name: readWrite
          db: test
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongod
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "100m"
                limits:
                  memory: "512Mi"
                  cpu: "250m"
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 1Gi
            storageClassName: gp3