apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongodb-secret-access-binding
subjects:
  - kind: ServiceAccount
    name: mongodb-database
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: mongodb-secret-access
  apiGroup: rbac.authorization.k8s.io