apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongodb-secret-access
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "patch"] 
